// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVUgXOG_IY83dKKku2AyR4UvUvFHRt6uU',
    appId: '1:577422934559:web:3bb1d9fe533fdf3bd00b2a',
    messagingSenderId: '577422934559',
    projectId: 'muniafu-hotel',
    authDomain: 'muniafu-hotel.firebaseapp.com',
    storageBucket: 'muniafu-hotel.appspot.com',
    measurementId: 'G-GCT1QBM3Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfEp1GT_076YdDQe_bdnZ3KPu-bUDuFO8',
    appId: '1:577422934559:android:9815f4131f61a5ced00b2a',
    messagingSenderId: '577422934559',
    projectId: 'muniafu-hotel',
    storageBucket: 'muniafu-hotel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_AAorcTyaLxtSi6EC2aquAkK9LgOumw',
    appId: '1:577422934559:ios:5a96556e975e9478d00b2a',
    messagingSenderId: '577422934559',
    projectId: 'muniafu-hotel',
    storageBucket: 'muniafu-hotel.appspot.com',
    iosBundleId: 'com.example.muniafuHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_AAorcTyaLxtSi6EC2aquAkK9LgOumw',
    appId: '1:577422934559:ios:5a96556e975e9478d00b2a',
    messagingSenderId: '577422934559',
    projectId: 'muniafu-hotel',
    storageBucket: 'muniafu-hotel.appspot.com',
    iosBundleId: 'com.example.muniafuHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVUgXOG_IY83dKKku2AyR4UvUvFHRt6uU',
    appId: '1:577422934559:web:e4a09b415cffe489d00b2a',
    messagingSenderId: '577422934559',
    projectId: 'muniafu-hotel',
    authDomain: 'muniafu-hotel.firebaseapp.com',
    storageBucket: 'muniafu-hotel.appspot.com',
    measurementId: 'G-WCNYR5TX21',
  );
}